//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DF_Perekhrestenko_IPZ_24_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz
    {
        public int Id { get; set; }
        public int RoomNumber { get; set; }
        public string Description { get; set; }
        public System.DateTime OrderDate { get; set; }
        public bool IsDone { get; set; }
        public Nullable<int> StaffId { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
